// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xesnchbfalqiqfgedhgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlc25jaGJmYWxxaXFmZ2VkaGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTA2MjIsImV4cCI6MjA1ODU4NjYyMn0.OxxNwak2MB4UN7zHDVMhf4yIV-zSh86Hde7ThLqPfEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);